### PR TITLE
Extract heatmap data assembly into helper

### LINKED ISSUE #6021: Profile heatmap doesn't work in Chrome 136
### URL

https://www.openstreetmap.org/user/TrickyFoxy

### How to reproduce the issue?

Open any active user profile

Version 136.0.7103.114 (Official Build) (arm64)
macOS 15

At least one of the users has everything running on Chrome 132

### Screenshot(s) or anything else?

Image

Firefox:

Image

### PR DESCRIPTION
**Pull request by hlfan**
Make the heatmap data generation more modular for yearly contribution calendars and address some points from the post merge discussion of #5998.
Also fixes #6021.

### CODE REVIEW

File: app/controllers/users_controller.rb [hunk 1]
```diff
@@ -2,6 +2,7 @@ class UsersController < ApplicationController
   include EmailMethods
   include SessionMethods
   include UserMethods
+  include HeatmapHelper
```
Comment (tomhughes) [inline app/controllers/users_controller.rb:5]: This should probably be a `HeatmapMethods` concern rather than a helper - helpers are primarily about adding methods to view, where they are made available automatically, while concerns are about extending models and controllers.

Comment (hlfan) [reply app/controllers/users_controller.rb]: I don't think it should have been in the controller at all.

**Review by tomhughes — APPROVED** [review]
Thanks. This looks good to me now.
