### PR TITLE
Avoid use of scientific notation in geocoder results

### LINKED ISSUE #4950: Searches for latitudes or longitudes between 1 and -1 result in invalid E-notation numbers
### URL

https://www.openstreetmap.org/search?query=0.0000123%2C0.0000456

### How to reproduce the issue?

Search for a coordinate within 1 degree of the equator or prime meridian, such as very near Greenwich or Ecuador. Note that the resulting coordinates are displayed in computery syntax like "1.23e-05" instead of "0.0000123". This may cause confusion or errors (for example if the values are copy-pasted into a program expecting plain decimal coordinates, or if average users are unfamiliar with E notation.)

This may in fact be an upstream issue with Nominatim, etc, in which case hopefully we can fix it there as well. This issue was discovered when a user attempted to import or access a bookmark with E notation coordinates inside of Organic Maps: it's unclear which software generated the offending geo: URI, but my understanding of the RFC and coordinate systems is that such a rendering should never be presented to end users and is generally unsupported in parsers. Since we often validate odd input on mobile against the OSM website and other OSM ecosystem tools, it makes sense to try and squash this bug wherever it's found.

Example queries:

https://www.openstreetmap.org/search?query=45.0%2C0.0000456

https://www.openstreetmap.org/search?query=0.0000123%2C-75.456

### Screenshot(s) or anything else?

_No response_

### PR DESCRIPTION
**Pull request by tomhughes**
This fixes #4950 by modifying the geocoder to avoid printing results in scientific notation.

The main fix is simply to avoid converting the user entered string to numeric format and back but for DMS style inputs we need to convert them to numeric form so we can do calculations so we use bigdecimal rather than float as it can force fixed precision format when converting to a string.

### CODE REVIEW

File: test/controllers/geocoder_controller_test.rb [hunk 1]
```diff
@@ -368,17 +368,17 @@ def latlon_check(query, lat, lon)
     assert_template :layout => "map"
     assert_equal %w[latlon osm_nominatim_reverse], assigns(:sources).pluck(:name)
     assert_nil @controller.params[:query]
-    assert_in_delta lat, @controller.params[:lat]
-    assert_in_delta lon, @controller.params[:lon]
+    assert_in_delta lat, @controller.params[:lat].to_f
+    assert_in_delta lon, @controller.params[:lon].to_f
```
Comment (AntonKhorev) [inline test/controllers/geocoder_controller_test.rb:372]:
```suggestion
    assert_match(/^[+-]?\d+(\.\d*)?$/, @controller.params[:lat])
    assert_match(/^[+-]?\d+(\.\d*)?$/, @controller.params[:lon])
    assert_in_delta lat, @controller.params[:lat].to_f
    assert_in_delta lon, @controller.params[:lon].to_f
```

File: test/controllers/geocoder_controller_test.rb [hunk 2]
```diff
@@ -368,17 +368,17 @@ def latlon_check(query, lat, lon)
...
     get search_path(:query => query), :xhr => true
     assert_response :success
     assert_template :search
     assert_template :layout => "xhr"
     assert_equal %w[latlon osm_nominatim_reverse], assigns(:sources).pluck(:name)
     assert_nil @controller.params[:query]
-    assert_in_delta lat, @controller.params[:lat]
-    assert_in_delta lon, @controller.params[:lon]
+    assert_in_delta lat, @controller.params[:lat].to_f
+    assert_in_delta lon, @controller.params[:lon].to_f
```
Comment (AntonKhorev) [inline test/controllers/geocoder_controller_test.rb:381]:
```suggestion
    assert_match(/^[+-]?\d+(\.\d*)?$/, @controller.params[:lat])
    assert_match(/^[+-]?\d+(\.\d*)?$/, @controller.params[:lon])
    assert_in_delta lat, @controller.params[:lat].to_f
    assert_in_delta lon, @controller.params[:lon].to_f
```

File: test/controllers/geocoder_controller_test.rb
Comment (AntonKhorev) [inline test/controllers/geocoder_controller_test.rb:1]: Shouldn't we test near-zero latlon values?

```ruby
  ##
  # Test identification of lat/lon pairs with values close to zero
  def test_identify_latlon_close_to_zero
    [
      "0.00001 -0.00002",
      "+0.00001 -0.00002"
    ].each do |code|
      latlon_check code, 0.00001, -0.00002
    end
  end
```

File: test/controllers/geocoder_controller_test.rb (hunk 1 above)
Comment (tomhughes) [reply test/controllers/geocoder_controller_test.rb:385]: Nice idea. I've added that and also added a test case using small values to check it doesn't trigger scientific formatting.

File: app/controllers/geocoder_controller.rb [hunk 3]
```diff
@@ -228,39 +224,20 @@ def normalize_params
...
-      lon = captures[9].casecmp("w").zero? ? -(captures[5].to_f + ((captures[6].to_f + (captures[7].to_f / 60)) / 60)) : captures[5].to_f + ((captures[6].to_f + (captures[7].to_f / 60)) / 60)
-    rescue StandardError
-      lat = captures[0].casecmp("s").zero? ? -(captures[1].to_f + ((captures[2].to_f + (captures[3].to_f / 60)) / 60)) : captures[1].to_f + ((captures[2].to_f + (captures[3].to_f / 60)) / 60)
-      lon = captures[5].casecmp("w").zero? ? -(captures[6].to_f + ((captures[7].to_f + (captures[8].to_f / 60)) / 60)) : captures[6].to_f + ((captures[7].to_f + (captures[8].to_f / 60)) / 60)
-    end
-    { :lat => lat, :lon => lon }
+    lat = ns * (nsd + (nsm / 60) + (nss / 3600))
+    lon = ew * (ewd + (ewm / 60) + (ews / 3600))
+
+    { :lat => lat.to_s("F"), :lon => lon.to_s("F") }
```
Comment (AntonKhorev) [inline app/controllers/geocoder_controller.rb:241]: Need to `.truncate()` to some reasonable precision before `.to_s` or else the length blows up:

image

**Review by AntonKhorev — CHANGES_REQUESTED** [review]

File: app/controllers/geocoder_controller.rb (hunk 3 above)
Comment (tomhughes) [reply app/controllers/geocoder_controller.rb]: Fixed... 
image

**Review by AntonKhorev — APPROVED** [review]

File: test/controllers/geocoder_controller_test.rb [hunk 4]
```diff
@@ -223,6 +223,18 @@ def test_identify_latlon_sw_dms
...
+  def test_identify_latlon_close_to_zero
+    [
+      "0.0000123 -0.0000456",
+      "+0.0000123 -0.0000456",
+      "N 0° 0' 0.4428\", W 0° 0' 1.6416\""
+    ].each do |code|
+      latlon_check code, 0.0000123, -0.0000456
+    end
+  end
+
```
Comment (AntonKhorev) [inline test/controllers/geocoder_controller_test.rb:237]: This one is going to fail with `TypeError: can't convert nil into BigDecimal`

```suggestion

  ##
  # Test identification of integer lat/lon pairs using N/E with degrees
  def test_identify_latlon_ne_d_int_deg
    [
      "N50° E14°"
    ].each do |code|
      latlon_check code, 50, 14
    end
  end
```

[Used to work correctly](https://www.openstreetmap.org/search?query=N50%C2%B0%20E14%C2%B0)

**Review by AntonKhorev — CHANGES_REQUESTED** [review]

File: test/controllers/geocoder_controller_test.rb (hunk 4 above)
Comment (tomhughes) [reply test/controllers/geocoder_controller_test.rb:250]: Ha that's effectively an old lurking bug - the first two regexps that are supposed to match the degrees only case but didn't allow the optional degree symbol while the rest of the regexps wrongly made everything after degrees optional so would over match.

All fixed now hopefuly...

File: test/controllers/geocoder_controller_test.rb [hunk 5]
```diff
@@ -60,6 +60,19 @@ def test_identify_latlon_ne_d
...
+    [
+      "N50 E14",
+      "N50° E14°",
+      "50N 14E",
+      "50°N 14°E"
+    ].each do |code|
+      latlon_check code, 50, 14
+    end
+  end
+
```
[the remark this answers is not in the document]
Comment (AntonKhorev) [reply test/controllers/geocoder_controller_test.rb:75]: If we don't want to identify them, we can change `\.\d*` to `\.\d+` in regexps.

[the remark this answers is not in the document]
Comment (tomhughes) [reply test/controllers/geocoder_controller_test.rb:75]: Fixed that now...

**Comment by AntonKhorev** [comment]
hopefully those were all the bugs, merged

**Comment by AntonKhorev** [comment]
and I was wrong, there's more
