### PR TITLE
Always do reverse geocoding when routing

### LINKED ISSUE #1874: Couldn't locate "..." with Directions and automatic reverse geocoding
Someone reported the following issue on the [German forum](https://forum.openstreetmap.org/viewtopic.php?id=62401) about some strange interaction between Directions and Automatic Reverse Geocoding. This could be some side effect of #1800.

How to reproduce:

1. Move to example location Lyon, Perrache, France
2. Context menu: set "from" location
3. Context menu: set different "to" location
4. Meanwhile from and to get automatically reverse geocoded.
5. Error message is shown about unknown locations ("Couldn't locate ...")

Pretty strange that the reverse geocoded location returned by Nominatim isn't know to Nominatim anymore at a later point in time.

I added a short video, hope that's ok to demonstrate the issue.

peek 2018-05-20 09-45

### LINKED ISSUE #1911: Directions interface does not use exact location when selected by right-clicking
#### Issue description
The directions interface does not use the location that I click. Instead it somehow snaps to a nearest 'node' or grid of some kind.

#### Steps to reproduce the issue
1. On the main map page, right-click on a location and select 'Directions from here'.
2. Right-click somewhere else and select 'Directions to here'.

#### What's the expected result?
I should get directions from the exact location I clicked first, to the exact location I clicked second.

#### What's the actual result?
I get directions from some point near the location I clicked first, to some point near the location I clicked second.

#### Additional details
- Directions between arbitrary points are not impossible for the engine, as is evidenced by manually clicking and dragging the start and end nodes of the generated directions to arbitrary locations (they do not snap back then).
- Possibly the cause of this behaviour is [here](https://github.com/openstreetmap/openstreetmap-website/blob/999b9c69e1af252610a2ad338d33d16273fcc22f/app/assets/javascripts/index/contextmenu.js#L22)? (I wanted to try it out but I couldn't get the dev env running)

### PR DESCRIPTION
**Pull request by AntonKhorev**
There was a number of bugs related to route endpoint locations caused by various reasons. Some of there reasons were already addressed. The one left is Nominatim deciding to do reverse geocoding when receiving something that looks like coordinates in its freeform query. The query itself is *not* a reverse geocoding query (`/reverse?...`), yet Nominatim will do reverse geocoding if it consists of two floating point numbers.

The problem is that we have inputs that can contain either addresses or coordinates. Then the seemingly obvious thing to get coordinates is to pass this input contents to Nominatim. And this is how you get bugs. It the input already contained coordinates, Nominatim would reverse-geocode them to some place and return the coordinates of that place that are different from the coordinates input already had. And then the endpoint marker would jump somewhere.

If we want to prevent this, we have to check ourselves if we already have two floating point numbers. If we do, we shouldn't make Nominatim's freeform geocoding query. Since we're going to parse coordinates inside the endpoint module to make that check, `endpoint.setValue` doesn't need its `latlng` argument and it is removed.

Since users probably expect reverse geocoding to be happening even if we had coordinates, `endpoint.setValue` is going to make a reverse-geocoding query explicitly, without overwriting the original coordinates. With changes here, `endpoint.setValue` works like this:
- The `value` parameter is checked if it's coordinates.
- If not, geocoding is performed. 
- If yes, reverse geocoding is done.

Reverse geocoding is also done on marker drag end.

Another thing that's done is caching of reverse geocoding results. The reason is that there are common scenarios when you get the same coordinates that were reverse-geocoded. For example, you set the starting point using the context menu, then you add the ending point. The context menu will open a directions url containing the same starting point coordinates, they were looked up already.

Another common scenario is swapping the route start/end. To avoid reverse-geocoding both ends again we can also swap their reverse-geocoding results. That's what `endpoint.swapCachedReverseGeocodes` does.

---

This should fix #1874 and #2982.

Also addresses #1910 to some extent. But if we want to get back "Paris" from the coordinates and not some address inside Paris, we'd need to pass along a zoom level. Nominatim [supposedly can use it](https://nominatim.org/release-docs/develop/api/Reverse/#result-restriction). Or pass search queries along. Presumably that wasn't done to [keep urls short](https://github.com/openstreetmap/openstreetmap-website/issues/1910#issuecomment-399255834), but we can pass only short queries for example.

Also should fix #1911 if the problem is markers moving from clicked locations to geocoding locations. In this case it's the step 3 of https://github.com/openstreetmap/openstreetmap-website/issues/2982#issuecomment-734512269.

May close #1754 because everything was rewritten.

### CODE REVIEW

**Comment by nenad-vujicic** [comment]
Thanks for great PR! The sources are now much more readable and it seems a lot of bugs are fixed.

Just a few remarks:

1. Perhaps it would be good to fit map's bounds (directions.js Ln 159) on union of markers and route polyline (instead of route polyline only). 2 cases when this is useful: 
a) at least one (or both) of markers are too far from retrieved route and they are not visible in final display and
b) routing engine was unable to return the route (e.g. place markers at (0,0) and (1,1)) and only markers are displayed (but, if you type them, map didn't focus on them).

2. It seems we still have duplicated calls to nominatim when we select from context menu (other cases are OK). Please, take a look at below video:

https://github.com/user-attachments/assets/2f7a4ed8-1e82-4eb4-becf-fd28a7c3e05c

Anyway, even with above remarks, I think this is great PR. Thanks for making it!

**Review by nenad-vujicic — APPROVED** [review]

**Comment by AntonKhorev** [comment]
> It seems is-invalid is not removed from inputs after successful contacting nominatim

They aren't removed in the original code either. The difference is it doesn't call nominatim, but it should have removed is-invalid as soon as the coordinates updated.

**Comment by AntonKhorev** [comment]
"2." form https://github.com/openstreetmap/openstreetmap-website/pull/5064#issuecomment-2285981589 - I only see one request to Nominatim happening when "Directions from/to here" is selected.

**Comment by nenad-vujicic** [comment]
> "2." form [#5064 (comment)](https://github.com/openstreetmap/openstreetmap-website/pull/5064#issuecomment-2285981589) - I only see one request to Nominatim happening when "Directions from/to here" is selected. I fixed something like this in [2d1cf4c](https://github.com/openstreetmap/openstreetmap-website/commit/2d1cf4c380442595d7a4629f3a4c79124277f12b) but wasn't it written before the comment?


https://github.com/user-attachments/assets/e5b3980e-4779-4104-8cc0-4b581a631ea4

If one point is valid and you change the second one, yes, there is only one request from nominatim. But, if one point is invalid and you change the second one, it will request from nominatim 2 times (once for each point).

I used the latest sources at the moment on which I applied this PR.

Thanks!

**Comment by AntonKhorev** [comment]
@nenad-vujicic how about now? I added caching of not found results from Nominatim.

**Comment by nenad-vujicic** [comment]
> @nenad-vujicic how about now? I added caching of not found results from Nominatim.

It's perfect now. Thank you very much!

There is one another issue, but probably not part of this PR. In some situations (take a look at attached video), on invalid search scene map fits to some other boundary box and route is displayed on wrong position. After pushing OK, it retrieves good route, displays it on good position and fits to good boundary box.

https://github.com/user-attachments/assets/05ddd792-be25-4990-bb54-1f1936d4f8c9

**Comment by AntonKhorev** [comment]
> In some situations (take a look at attached video), on invalid search scene map fits to some other boundary box and route is displayed on wrong position

Could be caused by `alert()`. I'll later remove them.

**Comment by AntonKhorev** [comment]
I guess this can be merged now. I don't think there's anything else worth taking out and merging separately.

File: app/assets/javascripts/index/directions-endpoint.js [hunk 1]
```diff
@@ -79,12 +111,32 @@ OSM.DirectionsEndpoint = function Endpoint(map, input, iconUrl, dragCallback, ch
...
+      endpoint.value = json[0].display_name;
       input.val(json[0].display_name);
 
       changeCallback();
     });
   }
 
+  function getReverseGeocode() {
+    var latlng = endpoint.latlng.clone();
+    var reverseGeocodeUrl = OSM.NOMINATIM_URL + "reverse?lat=" + latlng.lat + "&lon=" + latlng.lng + "&format=json";
```
Comment (tomhughes) [inline app/assets/javascripts/index/directions-endpoint.js:123]: Do we need to control the match precision here? Might this cause a location to "snap" to something a long way away?

**Review by tomhughes — COMMENTED** [review]
I'm not sure I agree with either part of the title of this PR as I don't really see any simplification - quite the opposite if anyway. The "always do reverse geocoding" is also misleading because it implies extending an existing use when in fact this introduces reverse geocoding for the first time?

File: app/assets/javascripts/index/directions-endpoint.js [hunk 2]
```diff
@@ -79,12 +111,32 @@ OSM.DirectionsEndpoint = function Endpoint(map, input, iconUrl, dragCallback, ch
...
+
+    endpoint.geocodeRequest = $.getJSON(reverseGeocodeUrl, function (json) {
+      delete endpoint.geocodeRequest;
+      if (!json || !json.display_name) {
+        input.addClass("is-invalid");
+        alert(I18n.t("javascripts.directions.errors.no_place", { place: endpoint.value }));
```
[the remark this answers is not in the document]
Comment (AntonKhorev) [reply app/assets/javascripts/index/directions-endpoint.js]: It shouldn't be an error but it currently is, that's why I kept it. That's not the only thing wrong about error handling here.

Removed `addClass` and `alert` now.

File: app/assets/javascripts/index/directions-endpoint.js (hunk 1 above)
Comment (AntonKhorev) [reply app/assets/javascripts/index/directions-endpoint.js:126]: The location wouldn't snap in the same way is does on the currently deployed version. The pointer is not going to move, just the address would be too imprecise.

Ultimately we should control the precision but I didn't want to do it in this pull request, see https://github.com/openstreetmap/openstreetmap-website/pull/4904#discussion_r1723165682

**Comment by AntonKhorev** [comment]
> in fact this introduces reverse geocoding for the first time?

Reverse geocoding happens in the deployed version when Nominatim decides to do it. I don't know if it's intentional or accidental.

- context menu, directions from/to here - reverse geocoding
- drag/drop a marker - no reverse geocoding
- type in coordinates - reverse geocoding if you typed two numbers with decimal points (or what's the logic for detecting coordinates in Nominatim), no reverse geocoding otherwise

**Comment by AntonKhorev** [comment]
> I'm not sure I agree with either part of the title of this PR as I don't really see any simplification - quite the opposite if anything.

A large part of this pull request is already merged with other pull request. The simplification here is that you don't have to pass `latlng` to `endpoint.setValue`.

**Comment by tomhughes** [comment]
> A large part of this pull request is already merged with other pull request

Can we rebase it then so we can see what's left?

**Comment by AntonKhorev** [comment]
Updated pull request description.

**Review by tomhughes — APPROVED** [review]
I've had another look through this, and played with a bit in my dev environment and I think it's probably good to merge now. Thanks for all the work on it.
