### PR TITLE
Fix some dark mode colors desyncing

### LINKED ISSUE #6537: Poor contrast on context menu in light theme
### URL

_No response_

### How to reproduce the issue?

When clicking on the new context menu, the link text becomes white; this is correct in the dark theme but produces an unreadable white-on-grey in the light theme.

### Screenshot(s) or anything else?

Image

### PR DESCRIPTION
**Pull request by hlfan**
- Removed the "cut-out" part from the GitHub icon, so the Invertocat is the `path` like the apple.
- Synced the used preferred color scheme to Bootstrap to prevent it from looking like this when the OSM user preference isn't the same as the browser one:
  image
- Used the dark grey that [GitHub provides](https://brand.github.com/foundations/logo) in https://brand.github.com/GitHub_Logos.zip
- Removed the overrides to invert the `.dropdown-item:active` style. This closes #6542 and fixes #6537.

### CODE REVIEW

**Review by tomhughes — COMMENTED** [review]
As fast as I can tell the icon related changes seem fine though it would have been helpful to have a bit more information about what you were doing as the linked issue is only about the menu.

The menu change does fix the current issues in dark mode, but the result has very little contrast between the background and the highlight, at least on this laptop, and the contrast in light mode is also reduced to the point where you can hardly see the bar.

**Comment by hlfan** [comment]
I updated the JS to increase the contrast.

**Comment by pablobm** [comment]
Where did you see about the special grey for the GitHub log? I can't see it on the page you linked. All I see is the phrase "The Invertocat and our wordmark should only appear in white, black, or in few cases grey".

On the topic of the contrast in the context menu, I see it diminished, before even hovering:

Production | This PR
--- | ---
Context menu as in production | Context menu as in this PR, with slightly but noticeably decreased contrast

File: app/assets/javascripts/index/contextmenu.js [hunk 1]
```diff
@@ -177,7 +177,7 @@ class ContextMenu {
   }
 
   _render(items) {
-    const $menuList = $("<ul>").addClass("dropdown-menu show shadow cm_dropdown_menu");
+    const $menuList = $("<ul>").addClass("dropdown-menu list-group show shadow cm_dropdown_menu");
```
Comment (gravitystorm) [inline app/assets/javascripts/index/contextmenu.js]: I don't think it's a good idea to try to make this styled as *both* a dropdown menu and also as a list-group. It shouldn't be both, these are two different bootstrap components.

```diff
-    const $menuList = $("<ul>").addClass("dropdown-menu list-group show shadow cm_dropdown_menu");
+    const $menuList = $("<ul>").addClass("dropdown-menu show shadow cm_dropdown_menu");
```

File: app/assets/stylesheets/common.scss [hunk 2]
```diff
@@ -995,25 +995,25 @@ img.trace_image {
...
+  .github-logo path { fill: #1b1f24; }
 }
 
 /* Rules for contextmenu */
 
 #map-context-menu {
   .dropdown-item {
     &:hover, &:active {
-      background-color: $gray-200;
+      @extend :focus;
```
Comment (gravitystorm) [inline app/assets/stylesheets/common.scss]: How about we just don't override the hover and active states at all, and let bootstrap deal with them? If we leave it alone, it works fine in both dark and light modes, as far as I can tell.

```diff
 #map-context-menu {
-  .dropdown-item {
-    &:hover, &:active {
-      @extend :focus;
-    }
-  }
   &.cm_dropdown {
```

File: app/assets/javascripts/index/contextmenu.js [hunk 3]
```diff
@@ -194,7 +194,7 @@ class ContextMenu {
     const $label = $("<span>").text(item.text);
 
     const $link = $("<a>")
-      .addClass("dropdown-item d-flex align-items-center gap-3")
+      .addClass("dropdown-item list-group-item-action d-flex align-items-center gap-3")
```
Comment (gravitystorm) [inline app/assets/javascripts/index/contextmenu.js]:
```diff
-      .addClass("dropdown-item list-group-item-action d-flex align-items-center gap-3")
+      .addClass("dropdown-item d-flex align-items-center gap-3")
```

**Comment by hlfan** [comment]
> Where did you see about the special grey for the GitHub log? I can't see it on the page you linked. All I see is the phrase "The Invertocat and our wordmark should only appear in white, black, or in few cases grey".

That's what is provided in:
- the logo files zip download: https://brand.github.com/GitHub_Logos.zip
- the logo color scheme demonstration below the text you're citing: https://brand.github.com/foundations/logo#coloring-the-logo

**Comment by gravitystorm** [comment]
Merged, thanks!

**Comment by mmd-osm** [comment]
Regarding the context menu, I think the hovering is barely visible now, both in light and dark mode. What was the reason again to make this worse than before?

This is how it looks like here. I'm hovering over the second item.

{42959EEB-A53D-4697-8131-2D2E0045C4EB}

**Comment by tomhughes** [comment]
Which I did point out and @hlfan said he had increased the contrast though I admit I don't see much difference myself from the original version.

**Comment by gravitystorm** [comment]
We're talking about several different things here when it comes to contrast. There's the foreground-background contrast levels of the text (in various states, hover, active, dark mode etc), and the background-background contrast between hovered and unhovered states.

@mmd-osm what this PR did was remove all the attempts to twiddle things. We were starting to layer fixes on top of fixes. Instead, we now just use the [bootstrap dropdown component defaults](https://getbootstrap.com/docs/5.3/components/dropdowns/). 

The background hover highlighting is subtle, but that's coming from upstream. I wouldn't call the end result "worse" because it fixed various other problems.

If we want to change the backgrounds of hovered items in dropdown menus, i.e. override the bootstrap defaults, then let's discuss that and make it work for all the dropdown menus consistently, rather than trying to adjust this one separately.

**Comment by mmd-osm** [comment]
> We were starting to layer fixes on top of fixes. Instead, we now just use the [bootstrap dropdown component defaults](https://getbootstrap.com/docs/5.3/components/dropdowns/).

I'm getting your idea to get rid of custom css logic, that's all fine. Still, if the resulting UI is subpar, these defaults may not be ideal.

>  then let's discuss that and make it work for all the dropdown menus consistently, rather than trying to adjust this one separately.

For real consistency, you would have to make the coloring match the other two places where we have popups today. They're using some green (`#7ebc6f`) as background color. I was a bit hesitant to go for that color for the new popup, but maybe that's an option? In any case, it has a significantly better background-background contrast than what we have now.

{B290971F-BD91-4AEB-943D-E2E10B215376}

{95110FEC-CCFD-4FB8-86D8-BDEBFA886EC2}
